rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender

appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n

# Package Flink ? riduci il rumore
logger.flink.name = org.apache.flink
logger.flink.level = WARN

logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

# Il nostro codice ? INFO per vedere i log
logger.smash.name = com.marbl.eventsmash
logger.smash.level = INFO